name: Build

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.100
      - name: Execute ci/build.sh
        run: ci/build.sh
      - name: Archive build artifacts
        uses: actions/upload-artifact@v1
        with:
          name: build
          path: build
